version: '3'
services:
  php:
    build: ./docker/php
    ports:
      - "9000"
    volumes:
      - ../source:/var/www/html
    hostname: php-host
    links:
      - rabbitmq

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .../source:/var/www/html
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    hostname: nginx-host

  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5671:5671"
      - "5672:5672"
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=eiGhao8o
